# Generated by Django 3.2.13 on 2022-05-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slugh',
            new_name='slug',
        ),
    ]
